@AgendaCerta_HostAddress = http://localhost:5135

### Listar todos os atendentes
GET {{AgendaCerta_HostAddress}}/api/atendente

### Buscar atendente por ID
GET {{AgendaCerta_HostAddress}}/api/atendente/1

### Buscar atendente por CPF
GET {{AgendaCerta_HostAddress}}/api/atendente/cpf/34567890013

### Buscar atendentes por especialidade
GET {{AgendaCerta_HostAddress}}/api/atendente/especialidade/Cardio

### Criar novo atendente
POST {{AgendaCerta_HostAddress}}/api/atendente
Content-Type: application/json

{
    "nome": "Denis Cornedo",
    "email": "deco@email.com",
    "telefone": "11999999999",
    "cpf": "34567890013",
    "especialidade": "Pediatria",
    "DataNascimento": "1979-01-12"
}

### Atualizar atendente
PUT {{AgendaCerta_HostAddress}}/api/atendente/1
Content-Type: application/json

{
    "nome": "João Silva Atualizado",
    "email": "joao.atualizado@exemplo.com",
    "telefone": "11988888888",
    "cpf": "12345678901",
    "especialidade": "Oftalmologia",
    "DataNascimento": "1995-10-20"
}

### Deletar atendente
DELETE {{AgendaCerta_HostAddress}}/api/atendente/3